import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.locator('body').click();
  await page.goto('https://www.google.com/sorry/index?continue=https://www.google.com/search%3Fq%3Ddemoblaze%26oq%3Ddemoblaze%26gs_lcrp%3DEgZjaHJvbWUyBggAEEUYOdIBCTE0NzcxajBqMqgCALACAA%26sourceid%3Dchrome%26ie%3DUTF-8%26sei%3DCQxRabzbM6GSseMPuvK1yQg&q=EhAkAUkAHHvhGZ319oCnvFXpGIqYxMoGIjCRbm9zaCBb_RBQ44Gik6BkvjlmtktgBCmKgchkT18fo-4gJYKOxbFe_ahYNgDP_o0yAVJaAUM');
  await page.locator('iframe[name="a-wtsxee6bov7q"]').contentFrame().getByRole('checkbox', { name: 'I\'m not a robot' }).click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="3"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="3"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="15"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="3"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="7"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="11"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="6"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="2"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().getByRole('button', { name: 'Next' }).click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="13"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="10"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="9"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="12"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="8"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().locator('[id="14"]').click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
  await page.locator('iframe[name="c-wtsxee6bov7q"]').contentFrame().getByRole('button', { name: 'Verify' }).click();
});